# ./.rubocop.yml
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*

Metrics/LineLength:
  Max: 180
  Exclude:
    - ./db/seeds.rb
    - ./config/initializers/*.rb

Metrics/BlockLength:
  Exclude:
    - ./spec/**/*_spec.rb
    - ./spec/**/*.rb

Metrics/MethodLength:
  Max: 30
  Exclude:
    - ./db/migrate/*.rb
    
Lint/AmbiguousBlockAssociation:
  Exclude:
    - ./spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Max: 20
