# ./.rubocop.yml
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*
    - ./db/migrate/20210316211119_create_doorkeeper_tables.rb
    - ./db/migrate/20210331011811_add_service_name_to_active_storage_blobs.active_storage.rb

Metrics/LineLength:
  Max: 180
  Exclude:
    - ./db/seeds.rb
    - ./config/initializers/*.rb

Metrics/BlockLength:
  Exclude:
    - ./spec/**/*_spec.rb
    - ./spec/**/*.rb
    - ./config/environments/development.rb
    - ./config/routes.rb
    - ./config/environments/production.rb

Metrics/MethodLength:
  Max: 30
  Exclude:
    - ./db/migrate/*.rb
    
Lint/AmbiguousBlockAssociation:
  Exclude:
    - ./spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Max: 20
